spring:
  batch:
    job:
      names: ${job.name:helloWorldJob}
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name:
    url: jdbc:mariadb://127.0.0.1:3306/Batch_25_06?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    show-sql: true